### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [dustymac/prj-rev-bwfs-dasmoto#2]
Excellent project, near perfect.  I look for two items in here, first how repetitive is your css.  Did you organize your content using divs.  Great on both regards.  

I know I brought up the minor repetition, but I will tell you in the later projects I have sometimes replace 30 to 50 lines of css with 3 to 6 lines.  The less you have in your css, the easier it is to debug.

As a challenge take a look at bootstrap, www.getbootstrap.com. See if you can incorporate it into this site and make it mobile friendly. This will help prepare you for the upcoming projects.

**Comment by dustymac** [comment]
Much appreciated Farish, will take a look at Bootstrap tonight.
